# Generated by Django 3.2.4 on 2026-02-13

import decimal
from django.core.validators import MinValueValidator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='GlassCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Категория стекла')),
            ],
            options={
                'verbose_name': 'Категория стекла',
                'verbose_name_plural': 'Категории стекла',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_type', models.CharField(choices=[('client', 'Клиент'), ('supplier', 'Поставщик')], max_length=20, verbose_name='Тип партнера')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
                'indexes': [models.Index(fields=['partner_type', 'name'], name='frontend_pa_partner_74f510_idx')],
            },
        ),
        migrations.CreateModel(
            name='GlassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Вид стекла')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='glass_types', to='frontend.glasscategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Вид стекла',
                'verbose_name_plural': 'Виды стекла',
                'ordering': ['category__name', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WarehouseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width_mm', models.PositiveIntegerField(verbose_name='Ширина (мм)')),
                ('height_mm', models.PositiveIntegerField(verbose_name='Высота (мм)')),
                ('thickness_mm', models.DecimalField(decimal_places=2, max_digits=6, validators=[MinValueValidator(decimal.Decimal('0.01'))], verbose_name='Толщина (мм)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество листов')),
                ('total_volume_m2', models.DecimalField(decimal_places=3, editable=False, max_digits=12, verbose_name='Общий объем (м²)')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[MinValueValidator(decimal.Decimal('0.00'))], verbose_name='Общая сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата прихода')),
                ('glass_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='frontend.glasstype', verbose_name='Вид стекла')),
                ('supplier', models.ForeignKey(limit_choices_to={'partner_type': 'supplier'}, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_receipts', to='frontend.partner', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Приход на склад',
                'verbose_name_plural': 'Приходы на склад',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sheets', models.PositiveIntegerField(default=0, verbose_name='Общее количество листов')),
                ('total_volume_m2', models.DecimalField(decimal_places=3, default=decimal.Decimal('0.000'), max_digits=12, verbose_name='Общий объем (м²)')),
                ('glass_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_balance', to='frontend.glasstype', verbose_name='Вид стекла')),
            ],
            options={
                'verbose_name': 'Остаток на складе',
                'verbose_name_plural': 'Остатки на складе',
            },
        ),
    ]
